# version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-net
    # --- Add this healthcheck block ---
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build: ./backend
    container_name: mern-backend
    restart: always
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/todos
    volumes:
      - ./backend:/app
      - /app/node_modules
    # --- Modify the depends_on block like this ---
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - mern-net
      
volumes:
  mongo-data:

networks:
  mern-net:
    driver: bridge
